import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';
import { AngularFireModule } from 'angularfire2';

// diretives and providers
import { Loader } from '../providers/loader';
import { Nl2br } from '../pipes/nl2br';

// Custom pages generated by ionic generator
import { Menu } from '../pages/menu/menu';
import { RoomSettingPage } from '../pages/setting/room-info/setting';
import { SettingsPage } from '../pages/menu/settings/settings';
import { HomePage } from '../pages/home/home';
import { PostPage } from '../pages/post/post';
import { UserPage } from '../pages/user/user';
import { QuestionDetailPage } from '../pages/mypage/question/question-detail/question-detail';
import { QuestionListPage } from '../pages/mypage/question/question-list/question-list';
import { CallNumberPage } from '../pages/call-number/call-number';
import { ImagePickerPage } from '../pages/image-picker/image-picker';
import { BuildCaseInputPage } from '../pages/buildCase/build-case-input/build-case-input';
import { ZipCodePage } from '../pages/zip-code/zip-code';
// Authentication
import { LoginPage } from '../pages/authentication/login/login';
import { RegistrationPage } from '../pages/authentication/registration/registration';
import { BuildCaseListPage } from '../pages/buildCase/build-case-list/build-case-list';
import { BuildCaseDetailPage } from '../pages/buildCase/build-case-detail/build-case-detail';
import { GeneralRegistrationPage } from '../pages/authentication/registration/general-user/registration';
import { BussinessManRegistrationPage } from '../pages/authentication/registration/buisnessman-user/registration';
//BussinessManRegistrationPage
import { Config } from './config'
import {PostService} from "../services/post-service";
import {UserService} from "../services/user-service";
import { Storage } from '@ionic/storage';
import {RoomService} from "../services/room-service";
import { ZipCodeService } from '../services/zip-code-service';

@NgModule({
  declarations: [
    MyApp,
    SettingsPage,
    Menu,
    LoginPage,
    Nl2br,
    HomePage,
    PostPage,
    UserPage,
    CallNumberPage,
    ImagePickerPage,
    BuildCaseListPage,
    BuildCaseDetailPage,
    GeneralRegistrationPage,
    BussinessManRegistrationPage,
    RoomSettingPage,
    QuestionDetailPage, // 사실상 채팅!
    QuestionListPage,
      BuildCaseInputPage,
      ZipCodePage
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    AngularFireModule.initializeApp(Config.FIREBASE_CONFIG)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    Menu,
    LoginPage,
    SettingsPage,
    HomePage,
    PostPage,
    UserPage,
    CallNumberPage,
    ImagePickerPage,
    BuildCaseListPage,
    BuildCaseDetailPage,
    GeneralRegistrationPage,
    BussinessManRegistrationPage,
    RoomSettingPage,
    QuestionDetailPage,
    QuestionListPage,
      BuildCaseInputPage,
      ZipCodePage
  ],
  providers: [
    Loader,
    Storage,
    PostService,
    RoomService,
    UserService,
      ZipCodeService
  ]
})
export class AppModule {}
